[[redirects]]
  from = "https://threadserver.netlify.app/:board/write"
  to = "/write.js"
  status = 200
  force = true

[[redirects]]
  from = "https://threadserver.netlify.app/:board"
  to = "/get.js"
  status = 200
  force = true

[build]
  functions = "/functions"